name: Run Tweet Del and Backup

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 16 * * 0"

jobs:
  twdel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run:
          pip install -r requirements.txt
      - name: Run
        env:
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BACKUP_KEY: ${{ secrets.BACKUP_KEY }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          BEFORE_DAYS: "7"
        run: python3 src/main.py
      - name: Setup git
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config --local user.name GitHubActions
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: Git push
        run: |
          git checkout main
          git pull origin main
          git add -A
          DIFF=`git diff --cached --numstat | wc -l`
          if [ $DIFF -eq 0 ]; then
            exit 0
          fi
          git commit -am 'GitHub Actions commit' --allow-empty
          git push origin main
