name: Rotate backup config

on:
  schedule:
    - cron: "10 4 3 * *"

jobs:
  twdel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: |
          echo "year=$(date +'%Y')" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Rotate
        run: |
          mkdir -p archives/${{ steps.date.outputs.year }}
          mv backup.json.enc archives/${{ steps.date.outputs.year }}/backup_${{ steps.date.outputs.date }}.json.enc
      - name: Setup git
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config --local user.name GitHubActions
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: Git push
        run: |
          git checkout main
          git pull origin main
          git add -A
          DIFF=`git diff --cached --numstat | wc -l`
          if [ $DIFF -eq 0 ]; then
            exit 0
          fi
          git commit -am 'GitHub Actions commit' --allow-empty
          git push origin main
